### ISSUE TITLE
Unsupported BodyInit type - RN 0.54

### ISSUE THREAD

**Issue by maxhungry** [jhen0409/react-native-debugger#209]
With React Native 0.54, when the option __Enable Network Inspect__ is turned on, you would get `Uncaught Error: unsupported BodyInit type`, this may have something to do with how `blob`s changed in 0.54.

React Native Debugger app version: 0.7.13
React Native version: 0.54.1
Platform: iOS & Android
Is real device of platform: Yes
Operating System: macOS

**Comment by ifiokjr** [comment]
I"m getting the same issue.

**Comment by alloy** [comment]
I’m seeing this issue with plain Chrome.app DevTools as well btw, so not just an issue with this app.

**Comment by Lxxyx** [comment]
React native bugs. Not debugger.

**Comment by sibelius** [comment]
maybe this could help https://github.com/Kureev/react-native-network-proxy

**Comment by jhen0409** [comment]
Fixed in #217. I'll release the new version later.

**Comment by alloy** [comment]
Unfortunately I’m still running into the same issue (I’m on RN 0.54.2 btw)

Alas I don’t have time to debug right away, but if this turns out to work for most other people then I’ll definitely try to find some time to debug on our end.

**Comment by jehartzog** [comment]
Thank you for pushing this fix so quickly!

I'm running 0.7.16 which should have fixed this issue with #217, but I am still seeing the same error as above. Let me know if I can help resolve this.

RN 0.54.2
Android development, actual device.
MacOS

**Comment by alloy** [comment]
Interestingly it works for me if I enable the network inspector _after_ the first request.

**Comment by jhen0409** [comment]
Due to we call [`the method`](https://github.com/jhen0409/react-native-debugger/blob/master/app/worker/index.js#L47) after import application script, so some `fetch` calls on global scope will be failed.

I just realized this mistake 🙈, I guess it may be the same as your case. @alloy @jehartzog

**Comment by toytonic** [comment]
Just gave it a try and unfortunately it does not work for me. I am running 0.7.17 and RN 0.54.2.
Also toggling the inspection after the first request as described by @alloy doesn't work.

Let me know if I can help.

**Comment by jhen0409** [comment]
@toytonic could you provide an example code?

**Comment by toytonic** [comment]
I must correct myself. Toggling after the first request DOES indeed work. Apparently there was an server issue on our end when debugging this. Sorry for the confusion.

However the issue persists when toggling it on before the first request or after a live reload. 

We are using this library for our requests: https://github.com/KnisterPeter/pretend

Which internally just uses the (native) fetch api.

**Comment by alloy** [comment]
Just gave the update a try and I’m also still seeing the problem under certain conditions:

1. Launch app
2. Enable Network Inspect
3. Open first RN view that makes a fetch
4. Receive `Unsupported BodyInit type` error on all views that make fetches
5. Reload JS (Command-R)
6. Now all fetches keep working

You can try this with the example app in [our RN repo](https://github.com/artsy/emission), but you will need to create an account with artsy.net

**Comment by jhen0409** [comment]
Thanks for the examples!

I think the issue of first request wil be fixed by https://github.com/jhen0409/react-native-debugger/commit/792549a400329159fbd768439b2d2f02a95f5095. I haven't yet release a new version but you can try it first by follow [the documentation](https://github.com/jhen0409/react-native-debugger/blob/master/docs/contributing.md). Let me know if it's fixed for you.

**Comment by alloy** [comment]
Yup that’s it! Works perfect now 👍 

Thanks for the fast fixes 👏

**Comment by sibelius** [comment]
@jhen0409 any plan to get a release for this fix?

**Comment by jhen0409** [comment]
@sibelius I think `v0.7.18` already included my all fixes, is that still have the bug for you?

**Comment by sibelius** [comment]
this is breaking on 0.7.18

when we add this to our entry .js file

```
global.XMLHttpRequest = global.originalXMLHttpRequest ?
  global.originalXMLHttpRequest :
  global.XMLHttpRequest;
global.FormData = global.originalFormData ?
  global.originalFormData :
  global.FormData;
```

without this, it works, but we can't inspect network

**Comment by tzilist** [comment]
We are also seeing this issue still. @sibelius comment works, however, we can't see the network requests either.

**Comment by alloy** [comment]
@sibelius I removed such code from our codebase and instead started using the contextual menu in the debugger app to enable network inspecting.

**Comment by sibelius** [comment]
![image](https://user-images.githubusercontent.com/2005841/38527037-2d8693fe-3c2f-11e8-8ced-bd549feb215d.png)

this is the contextual menu, gonna try again, and let your guys know

**Comment by kholiavko-roman** [comment]
I have an issue with  0.7.18 version, If I enable "Network inspect" in contextual menu.
`fetch.js:231 Uncaught Error: unsupported BodyInit type`

react-native: 0.55.2
OS: Ubuntu 17.10

**Comment by Freddy03h** [comment]
Same issue with react-native-debugger `0.7.18`, react-native `0.55.2`, macOS `10.13.4`

**Comment by alloy** [comment]
One possible difference I have been noticing is that maybe it’s due to RN version? We’re on RN 0.54

**Comment by kikoseijo** [comment]
After the query, 

`body = Blob {size: 609, type: "application/json"}`

And the conditional its not able to match its prototype, 

![screen shot 2018-04-15 at 20 59 30](https://user-images.githubusercontent.com/1528668/38782212-55672076-40f0-11e8-9170-b758c1f0df9d.png)

**Comment by fr1n63** [comment]
Still seeing the issue in 0.54.4, fails if the network inspector is enabled from load, doesn't log any network activity if enabled post launch.

**Comment by Anshiii** [comment]
i can see this issue after i updated  from 0.48.2 to 0.55.3

**Comment by Anshiii** [comment]
react-native:0.55.3
React Native Debugger 0.7.18
I can see this issue after i updated rn from 0.48.2 to 0.55.3...  
And then ,  i see the code where error be throw in `fetch.js`... 
So i do this...

```javascript
fetch(url, {
      method: 'GET',,
      headers,
      body:' ' //the code i added
    }
```
And then enable the network...  Luckily,everything were be ok~~
What is intriguing is that after i deleted the code `body:' ' ` ,there is no error more.

**Comment by sibelius** [comment]
this is working for on 0.53.3 using this https://github.com/jhen0409/react-native-debugger/issues/209#issuecomment-379917990

**Comment by dodsky** [comment]
react-native: 0.55.3
React Native Debugger 0.7.18

We removed the "network switch" snippet from `index` and enabled Network inspect in context menu. The issue went away after that. 

```
global.XMLHttpRequest = global.originalXMLHttpRequest ?
  global.originalXMLHttpRequest :
  global.XMLHttpRequest;
global.FormData = global.originalFormData ?
  global.originalFormData :
  global.FormData;
```

**Comment by jpudysz** [comment]
@sibelius , @dodsky 
Confirmed 👍

**Comment by jhen0409** [comment]
Currently we just fixed the specify Enable Network Inspect feature in RNDebugger, so it shouldn't work if you only did the [XHR replacement](https://github.com/jhen0409/react-native-debugger/blob/master/docs/network-inspect-of-chrome-devtools.md#how-it-works).

If you don't want to use the `Enable Network Inspect` feature RNDebugger, you can use the following code:

```js
global.XMLHttpRequest = global.originalXMLHttpRequest ?
  global.originalXMLHttpRequest :
  global.XMLHttpRequest;
global.FormData = global.originalFormData ?
  global.originalFormData :
  global.FormData;

fetch; // Ensure to get the lazy property

// RNDebugger only
if (window.__FETCH_SUPPORT__) {
  window.__FETCH_SUPPORT__.blob = false
}
```

And ensure the `Network Inspect` of RNDebugger is disabled.

I can reopen it if someone still have the issue.

**Comment by servocoder** [comment]
@jhen0409 No matter either I do the XHR replacement or enable `Network Inspect` feature I got the `fetch.js:231 Uncaught Error: unsupported BodyInit type` error.

The `fetch` works only both are disabled. Obviously I can't inspect the network in this case.

Seems this happens for Chrome Dev Tools as well. I doubt this is RND specific bug, anyway I couldn't find a solution, unfortunately.

react-native: 0.55.3
React Native Debugger 0.7.18

**Comment by sgript** [comment]
Same issue on:
react-native -> 0.55.0
react native debugger -> 0.7.18

**Comment by shanecav84** [comment]
This was an issue for me and my coworker @sbleon when running the remote debugger while developing with iOS. In the remote debugger, I think that all of the polyfills supplied by React Native supersede the native implementations in Chrome. This is why we need to [override the XMLHttpRequest polyfill with the native Chrome implementation](https://github.com/facebook/react-native/blob/0.45-stable/Libraries/Core/InitializeCore.js#L43-L53) to get network debugging working. As a result, we also need to override the RN polyfills with native Chrome implementations for objects used by the native XMLHttpRequest. My development environment is set up like so:

```javascript
if (typeof GLOBAL !== 'undefined') {
  // Route network requests through Chrome's native XMLHttpRequest
  GLOBAL.XMLHttpRequest = GLOBAL.originalXMLHttpRequest || GLOBAL.XMLHttpRequest;

  // Use native Blob for native XMLHttpRequest set above
  GLOBAL.Blob = GLOBAL.originalBlob || GLOBAL.Blob;

  // Use native FileReader to read native Blob set above
  GLOBAL.FileReader = GLOBAL.originalFileReader || GLOBAL.FileReader;
}
```

Related: #18818 #18740 #6025 #2538

**Comment by shanecav84** [comment]
I deleted my comment with my solution and moved it [here](https://github.com/facebook/react-native/issues/18818#issuecomment-399162418) because it's a React Native issue, not this debugger.

**Comment by ospfranco** [comment]
@shanecav84 Seems [previous link](https://github.com/facebook/react-native/issues/18818#issuecomment-399162418) has been closed due to inactivity, I had no issues until react-native 0.58, I just upgraded to 0.59 and now facing issues again.

**Comment by vitalii** [comment]
have the same issue after upgrade to 0.59

**Comment by declanelcocks** [comment]
Same for me after upgrading to 0.59

**Comment by abhijeetdhope** [comment]
Everything was working fine, we upgraded from 0.58 to 0.59 and this problem started showing up.
I have already tried everything mentioned up in the comments, nothings seems to be working.

**Comment by ospfranco** [comment]
I started using axios as a workaround, it is also not a bad idea since the fetch API had some problems on older models

**Comment by sseppola** [comment]
Got this problem when we upgraded to react-native 0.59.4 (from 0.57).
It was fixed by removing the workaround from https://github.com/jhen0409/react-native-debugger/issues/242
<img width="587" alt="Screen Shot 2019-04-18 at 19 44 40" src="https://user-images.githubusercontent.com/4065840/56380615-f4f2d880-6212-11e9-85d2-2dd3d83bd473.png">
React Native Debugger v0.9.7

**Comment by meshaabi** [comment]
> Got this problem when we upgraded to react-native 0.59.4 (from 0.57).
> It was fixed by removing the workaround from #242
> <img alt="Screen Shot 2019-04-18 at 19 44 40" width="587" src="https://user-images.githubusercontent.com/4065840/56380615-f4f2d880-6212-11e9-85d2-2dd3d83bd473.png">
> React Native Debugger v0.9.7
> Edit: Network inspect works as expected after removing the snippet ☝️

the fetch issue was resolved by removing the snippet, but network requests dont show up in the debugger anymore.

**Comment by Thomasn57** [comment]
> the fetch issue was resolved by removing the snippet, but network requests dont show up in the debugger anymore.

Same issue for me, removing the snippet worked but now the requests are invisible in the network tab

**Comment by KirbyMcKenzie** [comment]
@meshaabi @Thomasn57 - I'm having the same problem. Have either of you guys found a workaround?

**Comment by W1nstar** [comment]
I'm having the same problem,

react-native: 0.59.8
rn-debugger: 0.9.8

If I enable network debugging, I can see the network request completing but a console error pops up and the app does not continue
`
c:\RN\node_modules\react-native\Libraries\vendor\core\whatwg-fetch.js:279 Uncaught Error: unsupported BodyInit type
    at Response.Body._initBody (c:\RN\node_modules\react-native\Libraries\vendor\core\whatwg-fetch.js:279)
    at new Response (c:\RN\node_modules\react-native\Libraries\vendor\core\whatwg-fetch.js:450)
    at XMLHttpRequest.xhr.onload (c:\RN\node_modules\react-native\Libraries\vendor\core\whatwg-fetch.js:500)
`

I tried the snippet on the app's entry point, didn't work. If I change to using axios, it doesn't error, so I'm guessing it's a fetch thing

**Comment by KirbyMcKenzie** [comment]
@W1nstar - I found adding the following snippet in my app's entry point seems to work. 

```
global.XMLHttpRequest = global.originalXMLHttpRequest
 ? global.originalXMLHttpRequest
 : global.XMLHttpRequest
global.FormData = global.originalFormData
 ? global.originalFormData
 : global.FormData

fetch // Ensure to get the lazy property

if (window.__FETCH_SUPPORT__) {
 // it's RNDebugger only to have
 window.__FETCH_SUPPORT__.blob = false
} else {
 /*
  * Set __FETCH_SUPPORT__ to false is just work for `fetch`.
  * If you're using another way you can just use the native Blob and remove the `else` statement
  */
 global.Blob = global.originalBlob ? global.originalBlob : global.Blob
 global.FileReader = global.originalFileReader
   ? global.originalFileReader
   : global.FileReader
}
```

**Comment by louisholley** [comment]
if anyone else is having trouble, i found that using https://github.com/facebook/react-native/issues/18818#issuecomment-399162418 and commenting out the line `GLOBAL.blob = ...` is working after updating

**Comment by pbassut** [comment]
Also fails on RN 0.59.9

**Comment by HugoLiconV** [comment]
I'm, getting this error too. I have RN 0.59.10 and React Native Debugger 0.10.5
