### ISSUE TITLE
Network inspector is broken on RN 0.56

### ISSUE THREAD

**Issue by anderskev** [jhen0409/react-native-debugger#242]
React Native Debugger app version: 0.7.18
React Native version: 0.56-rc.4
Platform: iOS simulator
Is real device of platform: No, simulator
Operating System: macOS 10.13.5

It appears that React Native 0.56 has broken the network inspector. I'm actually not sure if this is an issue with react-native-debugger or Chrome, as it appears that has broken as well. I would be happy to work on a fix if someone could point me in the right direction. Thanks!

**Comment by jhen0409** [comment]
The main issue will be #244, it should affect the Network Inspect.

**Comment by liuqiang1357** [comment]
+1, Any solution?

**Comment by allaire** [comment]
I got it to work temporally by adding this to my project:

```
// https://github.com/jhen0409/react-native-debugger/issues/242
if (__DEV__) {
  /* eslint no-undef: 0 */
  XMLHttpRequest = GLOBAL.originalXMLHttpRequest
    ? GLOBAL.originalXMLHttpRequest
    : GLOBAL.XMLHttpRequest;
}
```

**Comment by CNDW** [comment]
react-native 0.56 polyfills the `global.Blob` which breaks the fetch polyfill's strict check, we have to restore the original `Blob` when using the latest react-native-debugger with react-native > 0.54
```js
if (__DEV__) {
  global.XMLHttpRequest = global.originalXMLHttpRequest ?
    global.originalXMLHttpRequest :
    global.XMLHttpRequest;
  global.FormData = global.originalFormData ?
    global.originalFormData :
    global.FormData;
  global.Blob = global.originalBlob ?
      global.originalBlob :
      global.Blob;
  global.FileReader = global.originalFileReader ?
      global.originalFileReader :
      global.FileReader;
}
```

**Comment by jhen0409** [comment]
Fixed by #247.

**Comment by fierysolid** [comment]
This bug appears to be back with **react-native@0.57.0** [this comment](https://github.com/jhen0409/react-native-debugger/issues/242#issuecomment-404191533) fixes it

**Comment by MrIceman** [comment]
this is still broken, unfortunately React Native seems to become more and more buggy

**Comment by hanssonfredrik** [comment]
> I got it to work temporally by adding this to my project:
> 
> ```js
> // https://github.com/jhen0409/react-native-debugger/issues/242
> if (__DEV__) {
>   /* eslint no-undef: 0 */
>   XMLHttpRequest = GLOBAL.originalXMLHttpRequest
>     ? GLOBAL.originalXMLHttpRequest
>     : GLOBAL.XMLHttpRequest;
> }
> ```

Where did you put this code?

**Comment by allaire** [comment]
@hanssonfredrik anywhere as long as it gets run. I put it in a development config file that is loaded in index.js

**Comment by Saqib-Shakil** [comment]
After adding the code I can see the request but no responses

**Comment by safweb89** [comment]
Does anyone figures out how to fix it?

**Comment by Donkey-Kurt** [comment]
> After adding the code I can see the request but no responses

+1
