### ISSUE TITLE
Can't type `/` in Dispatcher for an action type.

### ISSUE THREAD

**Issue by chandlervdw** [jhen0409/react-native-debugger#27]
We namespace our actions like so: `auth/SAVE_CREDENTIALS` but I can't type a forward slash inside the Dispatcher. It automatically focuses on searching for a react component, even if I have the React DevTools closed/hidden.

**Comment by jhen0409** [comment]
Ahh, it looks related to react inspector ([it listen slash key](https://github.com/facebook/react-devtools/blob/cf0578966baf954038b7a8217165603133ee9af1/frontend/SearchPane.js#L56)), this can be a bug for `react-devtools` because it also broken type `/` to component props.

**Comment by jhen0409** [comment]
It should fixed in [`v0.5.3`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.5.3).

**Comment by julienvincent** [comment]
@jhen0409 Currently using `v0.5.4` and this issue is still present.

**Comment by jhen0409** [comment]
Sorry about that, looks like I haven't handle div of `contenteditable`, I'll fix it and publish `0.5.5` at later.

**Comment by jhen0409** [comment]
[`v0.5.5`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.5.5) is released. :)

**Comment by julienvincent** [comment]
Thanks!
