### ISSUE TITLE
Apollo dev tool is broken for Apollo Client 3.0

### ISSUE THREAD

**Issue by changLiuUNSW** [jhen0409/react-native-debugger#552]
I just recently upgrade my app from apollo client v2 to v3 and the apollo dev tool keeps crashing by throwing 
```
RNDebuggerWorker.js:2 Uncaught TypeError: r.queryManager.mutationStore.getStore is not a function
    at te.<anonymous> (RNDebuggerWorker.js:2)
    at te.s.emit (RNDebuggerWorker.js:2)
    at RNDebuggerWorker.js:2
    at RNDebuggerWorker.js:2
```
![image](https://user-images.githubusercontent.com/7379922/100941716-2df9d100-354e-11eb-93db-f4d1ef008ad8.png)

I have done some research and find out this on apollo-client-devtools github readme file
```
If you are running Apollo Client 2.0, the dev tools require at least apollo-client@2.0.0-rc.2 and react-apollo@2.0.0-beta.0, and you must be running at least version 2.0.5 of the dev tools themselves.

If you are running Apollo Client 3.0, you must be running at least version 2.3.3 of the dev tools.
```

Can we upgrade apollo-client-devtools to at least version 2.3.3 ?

**Comment by changLiuUNSW** [comment]
I have raised a PR 
https://github.com/jhen0409/react-native-debugger/pull/553

**Comment by GollyJer** [comment]
Most def need this. We just ran into the same problem.

**Comment by jhen0409** [comment]
Fixed in v0.11.6.

**Comment by extjbhlego** [comment]
Just updated to 11.6, but still can't see the cache 😄 

However, if I write `window.__APOLLO_CLIENT__.cache.data.data` in the console, I can see plenty of data

https://gyazo.com/1ccce5c86065d690e85ef6b29cf16905

**Comment by Legym** [comment]
I know this issue has been closed, but I am still seeing this issue. Same error as OP.

I have the most recent version of RND 0.11.6. and my apollo version is using 3.3.6. Any suggestions?

**Comment by changLiuUNSW** [comment]
@Legym 
The error should be gone once u upgraded to the latest version but u will get another issue
https://github.com/jhen0409/react-native-debugger/issues/565

**Comment by sebastienbarre** [comment]
Using 3.0 client as well, and I get exactly nothing in the Apollo dev tools. The cache is empty, even tho I can see the Apollo cache is being leveraged for sure in my app.

**Comment by danieldauk** [comment]
> Using 3.0 client as well, and I get exactly nothing in the Apollo dev tools. The cache is empty, even tho I can see the Apollo cache is being leveraged for sure in my app.

@sebastienbarre try passing `connectToDevTools: true` to the ApolloClient constructor.

**Comment by sebastienbarre** [comment]
@danieldauk thanks, that did the trick.
